### ISSUE TITLE
All crawls fails

### ISSUE THREAD

**Issue by bornakke** [medialab/hyphe#164]
All crawls on our new instance suddely fails. I have attempted to git pull the last version, but that didn't fix it. In the log files there is no error the only feedback is that hyphe says that it were "UNSUCCESSFUL".

Do you have any suggestions as to what can cause this? And if not how one could go about debugging the error? Is scrapy log files e.g. located somewhere else?

Best
Tobias

**Comment by bornakke** [comment]
I have now found the error causing it in the scrapy log file:

2016-03-10 12:34:02+0100 [-] Process started:  project='hyphe.magteliten' spider='pages' job='fc42a5eee6b311e5841f005056a52840' pid=16481 log='/var/log/scrapyd/hyphe.magteliten/pages/fc42a5eee6b311e5841f005056a52840.log' items=None
2016-03-10 12:34:02+0100 [HTTPChannel,130,127.0.0.1] 127.0.0.1 - - [10/Mar/2016:11:34:02 +0000] "GET /listjobs.json?project=hyphe.magteliten HTTP/1.0" 200 124 "-" "Twisted PageGetter"
2016-03-10 12:34:03+0100 [Launcher,16481/stderr] /tmp/hyphe.magteliten-20160224-091209-iz4yYM.egg/hcicrawler/spiders/pages.py:37: ScrapyDeprecationWarning: hcicrawler.spiders.pages.PagesCrawler inherits from deprecated class scrapy.spider.BaseSpider, please inherit from scrapy.spider.Spider. (warning only on first subclass, there may be others)
2016-03-10 12:34:03+0100 [Launcher,16481/stderr] Traceback (most recent call last):
	  File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
	    "__main__", fname, loader, pkg_name)
	  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
	    exec code in run_globals
	  File "/usr/lib/pymodules/python2.7/scrapyd/runner.py", line 39, in <module>
2016-03-10 12:34:03+0100 [Launcher,16481/stderr]     main()
	  File "/usr/lib/pymodules/python2.7/scrapyd/runner.py", line 36, in main
	    execute()
	  File "/usr/lib/pymodules/python2.7/scrapy/cmdline.py", line 143, in execute
	    _run_print_help(parser, _run_command, cmd, args, opts)
	  File "/usr/lib/pymodules/python2.7/scrapy/cmdline.py", line 89, in _run_print_help
	    func(*a, **kw)
	  File "/usr/lib/pymodules/python2.7/scrapy/cmdline.py", line 150, in _run_command
	    cmd.run(args, opts)
	  File "/usr/lib/pymodules/python2.7/scrapy/commands/crawl.py", line 60, in run
	    self.crawler_process.start()
	  File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 92, in start
	    if self.start_crawling():
	  File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 124, in start_crawling
	    return self._start_crawler() is not None
	  File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 139, in _start_crawler
2016-03-10 12:34:03+0100 [Launcher,16481/stderr]     crawler.configure()
	  File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 47, in configure
	    self.engine = ExecutionEngine(self, self._spider_closed)
	  File "/usr/lib/pymodules/python2.7/scrapy/core/engine.py", line 64, in __init__
	    self.downloader = downloader_cls(crawler)
	  File "/usr/lib/pymodules/python2.7/scrapy/core/downloader/__init__.py", line 73, in __init__
	    self.handlers = DownloadHandlers(crawler)
	  File "/usr/lib/pymodules/python2.7/scrapy/core/downloader/handlers/__init__.py", line 24, in __init__
	    dh = cls(crawler.settings)
	  File "/usr/lib/pymodules/python2.7/scrapy/core/downloader/handlers/http11.py", line 31, in __init__
	    self._contextFactoryClass = load_object(settings['DOWNLOADER_CLIENTCONTEXTFACTORY'])
	  File "/usr/lib/pymodules/python2.7/scrapy/utils/misc.py", line 42, in load_object
	    raise ImportError("Error loading object '%s': %s" % (path, e))
	ImportError: Error loading object 'hcicrawler.webclient.CustomSSLContextFactory': cannot import name ClientTLSOptions
2016-03-10 12:34:03+0100 [-] Process died: exitstatus=1  project='hyphe.magteliten' spider='pages' job='fc42a5eee6b311e5841f005056a52840' pid=16481 log='/var/log/scrapyd/hyphe.magteliten/pages/fc42a5eee6b311e5841f005056a52840.log' items=None

**Comment by boogheta** [comment]
Hi @bornakke, we had to add new dependencies to handle some new https protocols, so you need to run the following to update your existing install:

```bash
sudo pip uninstall cffi cryptography pyOpenSSL ndg-httpsclient pyasn1 
sudo pip install cffi cryptography pyOpenSSL ndg-httpsclient pyasn1 
sudo service scrapyd restart
```

**Comment by bornakke** [comment]
Done that but still gets exactly the same error.

**Comment by bornakke** [comment]
I do get this error when following your suggestions:

  Found existing installation: pyOpenSSL 0.13
    Not uninstalling pyOpenSSL at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: pyasn1 0.1.7
    Not uninstalling pyasn1 at /usr/lib/python2.7/dist-packages, owned by OS

**Comment by boogheta** [comment]
What if you run 
```bash
sudo pip install --upgrade pyOpenSSL pyasn1

**Comment by bornakke** [comment]
Did that already. The system insists on not uninstalling the package.

**Comment by boogheta** [comment]
What about 
```bash
sudo pip install urllib3[secure]
```
?

**Comment by bornakke** [comment]
Same problem. 
 Found existing installation: urllib3 1.7.1
    Not uninstalling urllib3 at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: pyasn1 0.1.7
    Not uninstalling pyasn1 at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: pyOpenSSL 0.13
    Not uninstalling pyOpenSSL at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: six 1.5.2
    Not uninstalling six at /usr/lib/python2.7/dist-packages, owned by OS
  Found existing installation: setuptools 3.3
    Not uninstalling setuptools at /usr/lib/python2.7/dist-packages, owned by OS
Successfully installed urllib3 pyasn1 certifi pyOpenSSL six setuptools

**Comment by bornakke** [comment]
I sound like I have to uninstall a number of repositiory packages (http://askubuntu.com/questions/683601/how-to-upgrade-python-setuptools-12-2-on-ubuntu-15-04)

**Comment by boogheta** [comment]
indeed it sounds like you have things such as python-openssl, python-pyasn1 etc alread installed, you should remove them with `sudo apt-get remove` then run the `sudo pip install`

**Comment by bornakke** [comment]
Did it and now hyphe cannot even start

hyphe@ethoslab:~/hyphe$ bin/hyphe start
Starting Hyphe's Python core JsonRPC API...
...started...
ERROR: Could not start Hyphe's backend server properly. See log below:

2016-03-10 15:39:18+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2016-03-10 15:39:18+0100 [-] Site starting on 6978
2016-03-10 15:39:18+0100 [-] Starting factory <twisted.web.server.Site instance at 0x7f436440e560>
2016-03-10 15:39:20+0100 [ERROR - --test-corpus--] Couldn't deploy crawler
2016-03-10 15:39:20+0100 [-] Received SIGTERM, shutting down.
2016-03-10 15:39:20+0100 [-] (TCP Port 6978 Closed)
2016-03-10 15:39:20+0100 [-] Stopping factory <twisted.web.server.Site instance at 0x7f436440e560>
2016-03-10 15:39:21+0100 [MongoProtocol,client] Received SIGTERM, shutting down.
2016-03-10 15:39:22+0100 [MongoProtocol,client] Received SIGTERM, shutting down.
2016-03-10 15:39:23+0100 [MongoProtocol,client] Received SIGTERM, shutting down.
2016-03-10 15:39:24+0100 [MongoProtocol,client] Received SIGTERM, shutting down.
2016-03-10 16:18:00+0100 [-] Log opened.
2016-03-10 16:18:00+0100 [-] twistd 15.5.0 (/home/hyphe/.virtualenvs/hyphe/bin/python 2.7.6) starting up.
2016-03-10 16:18:00+0100 [-] reactor class: twisted.internet.epollreactor.EPollReactor.
2016-03-10 16:18:00+0100 [-] Site starting on 6978
2016-03-10 16:18:00+0100 [-] Starting factory <twisted.web.server.Site instance at 0x7f42f62f11b8>
2016-03-10 16:18:22+0100 [ERROR - --test-corpus--] Couldn't destroy scrapyd spider: {u'status': u'error', u'message': u"[Errno 2] No such file or directory: '/var/lib/scrapyd/eggs/hyphe.--test-corpus--'"}
2016-03-10 16:18:22+0100 [-] All tests passed. Ready!
2016-03-10 16:18:22+0100 [-] Received SIGTERM, shutting down.
2016-03-10 16:18:22+0100 [-] (TCP Port 6978 Closed)
2016-03-10 16:18:22+0100 [-] Stopping factory <twisted.web.server.Site instance at 0x7f42f62f11b8>
2016-03-10 16:18:23+0100 [-] Received SIGTERM, shutting down.
2016-03-10 16:18:24+0100 [-] Received SIGTERM, shutting down.
2016-03-10 16:18:25+0100 [-] Received SIGTERM, shutting down.
2016-03-10 16:18:26+0100 [-] Received SIGTERM, shutting down.
hyphe@ethoslab:~/hyphe$

**Comment by boogheta** [comment]
any stacktrace in /var/log/scrapyd/scrapyd.err or scrapyd.log ?

**Comment by boogheta** [comment]
and in scrapyd.out maybe ?

Might be worth trying to restart hyphe a second time also, although I guess you already did that.

PS: remember you can always show up on our irc, that would make debugging reactively way easier :)

**Comment by bornakke** [comment]
Don't know what I have done but now it works. Thank you :)

**Comment by boogheta** [comment]
Great! :D 
Although while you're at it, I recommand you pull again and restart, I just fixed a bug that can easily become annoying :)

**Comment by bornakke** [comment]
Sorry I were too quick. Hyphe now starts, but the original error now allowing us to crawl persist (i have just pulled and restarted, but it didn't change anything):

2016-03-11 14:57:44+0100 [-] Process started:  project='hyphe.magteliten' spider='pages' job='37d0edb8e79111e591d3005056a52840' pid=566 log='/var/log/scrapyd/hyphe.magteliten/pages/37d0edb8e79111e591d3005056a52840.log' items=None
2016-03-11 14:57:44+0100 [HTTPChannel,4825,127.0.0.1] 127.0.0.1 - - [11/Mar/2016:13:57:44 +0000] "GET /listjobs.json?project=hyphe.magteliten HTTP/1.0" 200 4145 "-" "Twisted PageGetter"
2016-03-11 14:57:45+0100 [Launcher,566/stderr] /tmp/hyphe.magteliten-20160224-091209-_Mb8eP.egg/hcicrawler/spiders/pages.py:37: ScrapyDeprecationWarning: hcicrawler.spiders.pages.PagesCrawler inherits from deprecated class scrapy.spider.BaseSpider, please inherit from scrapy.spider.Spider. (warning only on first subclass, there may be others)
2016-03-11 14:57:45+0100 [Launcher,566/stderr] Traceback (most recent call last):
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] "__main__", fname, loader, pkg_name)
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] exec code in run_globals
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapyd/runner.py", line 39, in <module>
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] main()
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapyd/runner.py", line 36, in main
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] execute()
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/cmdline.py", line 143, in execute
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] _run_print_help(parser, _run_command, cmd, args, opts)
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/cmdline.py", line 89, in _run_print_help
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] func(*a, **kw)
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/cmdline.py", line 150, in _run_command
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] cmd.run(args, opts)
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/commands/crawl.py", line 60, in run
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] self.crawler_process.start()
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 92, in start
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] if self.start_crawling():
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 124, in start_crawling
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] return self._start_crawler() is not None
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 139, in _start_crawler
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] crawler.configure()
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/crawler.py", line 47, in configure
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] self.engine = ExecutionEngine(self, self._spider_closed)
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/core/engine.py", line 64, in __init__
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] self.downloader = downloader_cls(crawler)
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/core/downloader/__init__.py", line 73, in __init__
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] self.handlers = DownloadHandlers(crawler)
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/core/downloader/handlers/__init__.py", line 24, in __init__
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] dh = cls(crawler.settings)
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/core/downloader/handlers/http11.py", line 31, in __init__
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] self._contextFactoryClass = load_object(settings['DOWNLOADER_CLIENTCONTEXTFACTORY'])
2016-03-11 14:57:45+0100 [Launcher,566/stderr]   File "/usr/lib/pymodules/python2.7/scrapy/utils/misc.py", line 42, in load_object
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [Launcher,566/stderr] raise ImportError("Error loading object '%s': %s" % (path, e))
2016-03-11 14:57:45+0100 [Launcher,566/stderr] ImportError
2016-03-11 14:57:45+0100 [Launcher,566/stderr] :
2016-03-11 14:57:45+0100 [Launcher,566/stderr] Error loading object 'hcicrawler.webclient.CustomSSLContextFactory': cannot import name ClientTLSOptions
2016-03-11 14:57:45+0100 [Launcher,566/stderr] 
2016-03-11 14:57:45+0100 [-] Process died: exitstatus=1  project='hyphe.magteliten' spider='pages' job='37d0edb8e79111e591d3005056a52840' pid=566 log='/var/log/scrapyd/hyphe.magteliten/pages/37d0edb8e79111e591d3005056a52840.log' items=None

**Comment by boogheta** [comment]
can we chat please?

**Comment by boogheta** [comment]
I feel like we would go a lot faster if we could exchange directly, in the mean time (i.e. the week-end), if you can give me the output of
```sudo pip freeze```

**Comment by bornakke** [comment]
Hi Boogheta,

You are completly right - IRC would be the place to do this. I have just been really busy the last two days. Below the pip freeze. If this doesn't work then I will try to catch you on irc on monday - would that be possible?

Best
Tobias

Landscape-Client==14.12
MySQL-python==1.2.3
PAM==0.4.2
Scrapy==0.24.6
Scrapyd==1.0
Twisted==13.2.0
Twisted-Conch==13.2.0
Twisted-Core==13.2.0
Twisted-Lore==13.2.0
Twisted-Mail==13.2.0
Twisted-Names==13.2.0
Twisted-News==13.2.0
Twisted-Runner==13.2.0
Twisted-Web==13.2.0
Twisted-Words==13.2.0
argparse==1.2.1
certifi==2016.2.28
cffi==1.5.2
chardet==2.0.1
colorama==0.2.5
configobj==4.7.2
cryptography==1.2.3
cssselect==0.9.1
enum34==1.1.2
gevent==1.1rc3
greenlet==0.4.9
html5lib==0.999
idna==2.0
ipaddress==1.0.16
lxml==3.3.3
ndg-httpsclient==0.4.0
pbr==1.8.1
pyOpenSSL==0.13
pyasn1==0.1.7
pycparser==2.14
pycrypto==2.6.1
pyinotify==0.9.4
pymongo==2.7
pyserial==2.6
pystache==0.5.4
python-apt==0.9.3.5ubuntu2
queuelib==1.4.2
requests==2.2.1
selenium==2.42.1
service-identity==16.0.0
simplejson==3.8.2
six==1.5.2
stevedore==1.10.0
thrift==0.9.3
txmongo==0.6
urllib3==1.7.1
virtualenv==13.1.2
virtualenv-clone==0.2.6
virtualenvwrapper==4.7.1
w3lib==1.13.0
wheel==0.24.0
wsgiref==0.1.2
zope.interface==4.0.5

**Comment by boogheta** [comment]
I'll be around on IRC this afternoon

**Comment by bornakke** [comment]
Still there? I'm there now.

**Comment by boogheta** [comment]
note for later, trying the docker install might help avoiding all of the scrapyd mess

**Comment by bornakke** [comment]
Hi Boogheta,

I just want to inform you that the problem we were experiencing might not be limited to our setup. We are installing it on a completly clean server and also here does the scrapyd server not seem to start. 

I'm trying the new docker approach now and hopefully this will solve the problem.

**Comment by bornakke** [comment]
IRC?

**Comment by boogheta** [comment]
Hi @Bornakke, sorry wasn't available friday and won't be much more in the next few days, but I'd be happy to know more (which ubuntu version is this btw?). You can always try me during weekdays from 10 to 19 on IRC and I'll help if I get some time.

Most probably the problem comes from scrapyd's new versions not working as we are many to regularly point it out to them https://github.com/scrapy/scrapyd/issues/100 https://github.com/scrapy/scrapyd/issues/102 https://github.com/scrapy/scrapyd/issues/103
I might end up embedding a working scrapyd version along with hyphe at some point if this keeps going on although I'd rather not as that's really not clean nor straightforward.

I know the docker way of installing is a bit longer but easier, hope you get some luck with it, let me know!

**Comment by bornakke** [comment]
i'm closing this issue since it seems to be a sub-issue of a more general package problem (see https://github.com/medialab/hyphe/issues/169)
