### ISSUE TITLE
indexing taking ages

### ISSUE THREAD

**Issue by updiversity** [medialab/hyphe#200]
Hi,

I have been able to successfully harvest a specific web entity. In the sense, that by inspecting the mongodb collections pages and logs, everything looks OK.

The number of pages crawled are 2220. However the indexing looks to be stuck. The GUI keeps telling me : 2220 not indexed yet.

the only logs I have been able to catch (except from the crawler), are these ones:

2016-11-07T16:43:39+0000 [INFO - test12] Successfully deployed crawler
2016-11-07T16:43:42+0000 [INFO - test12] New corpus created
2016-11-07T16:43:42+0000 [INFO - test12] Starting corpus...
2016-11-07T16:43:42+0000 [INFO - test12] Starting MemoryStructure on port 13502 with 256Mo ram for at least 1800s (2304Mo ram and 9 ports left)
2016-11-07T16:43:42+0000 [INFO - test12] MemoryStructure ready
2016-11-07T16:43:43+0000 [INFO - test12] Saves default WE creation rule
2016-11-07T16:44:10+0000 [INFO - test12] Collecting WebEntities and WebEntityLinks...
2016-11-07T16:44:10+0000 [INFO - test12] ...ramcached.
2016-11-07T16:44:10+0000 [INFO - test12] Processing new WebEntity links...
2016-11-07T16:44:10+0000 [INFO - test12] ...processed new WebEntity links in 0.114318132401s.
2016-11-07T16:44:33+0000 [INFO - test12] Processing new WebEntity links...
2016-11-07T16:44:33+0000 [INFO - test12] ...processed new WebEntity links in 0.0179758071899s.
2016-11-07T16:44:46+0000 [INFO - test12] Indexing 1 pages from job 791ef748-a509-11e6-8266-08002714f593...
2016-11-07T16:46:43+0000 [INFO - test12] Generating WebEntities network...
2016-11-07T16:46:43+0000 [INFO - test12] ...JSON network generated in 0.000460863113403s
2016-11-07T17:18:42+0000 [INFO - test12] Stopping after 1908s of inactivity
2016-11-07T17:19:01+0000 [INFO - test12] MemoryStructure stopped
2016-11-07T17:20:52+0000 [INFO - test12] Starting corpus...
2016-11-07T17:20:52+0000 [INFO - test12] Starting MemoryStructure on port 13503 with 256Mo ram for at least 1800s (2304Mo ram and 9 ports left)
2016-11-07T17:20:52+0000 [INFO - test12] MemoryStructure ready
2016-11-07T17:20:54+0000 [INFO - test12] Collecting WebEntities and WebEntityLinks...
2016-11-07T17:20:54+0000 [INFO - test12] ...ramcached.
2016-11-07T17:20:54+0000 [WARNING - test12] Indexing job declared as running but probably crashed, trying to restart it.
2016-11-07T17:20:54+0000 [INFO - test12] Indexing 100 pages from job 791ef748-a509-11e6-8266-08002714f593...
2016-11-07T17:56:44+0000 [INFO - test12] Generating WebEntities network...
2016-11-07T17:56:44+0000 [INFO - test12] ...JSON network generated in 0.00816583633423s

that I collected through this command-line : 
cat hyphe-core.log | grep test12

first, is it normal it is taking ages to index ?
second, if a problem occurs during the indexing, where can i find the corresponding logs ?

**Comment by updiversity** [comment]
Just found further logs, still in the same file... don't know however if it is related....

2016-11-07T17:20:54+0000 [WARNING - test12] Indexing job declared as running but probably crashed, trying to restart it.
2016-11-07T17:20:54+0000 [twisted.python.log#info] "127.0.0.1" - - [07/Nov/2016:17:20:54 +0000] "POST // HTTP/1.1" 200 75657 "http://192.168.56.102/hyphe/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Ubuntu Chromium/53.0.2785.143 Chrome/53.0.2785.143 Safari/537.36"
2016-11-07T17:20:54+0000 [INFO - test12] Indexing 100 pages from job 791ef748-a509-11e6-8266-08002714f593...
2016-11-07T17:20:54+0000 [twisted.internet.defer#critical] Unhandled error in Deferred:
2016-11-07T17:20:54+0000 [twisted.internet.defer#critical] 
	Traceback (most recent call last):
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 496, in errback
	    self._startRunCallbacks(fail)
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 563, in _startRunCallbacks
	    self._runCallbacks()
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 649, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1316, in gotResult
	    _inlineCallbacks(r, g, deferred)
	--- <exception caught here> ---
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/vagrant/hyphe/hyphe_backend/core.tac", line 1879, in index_batch_loop
	    res = yield self.index_batch(page_items, job, corpus=corpus)
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1258, in _inlineCallbacks
	    result = result.throwExceptionIntoGenerator(g)
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/failure.py", line 389, in throwExceptionIntoGenerator
	    return g.throw(self.type, self.value, self.tb)
	  File "/home/vagrant/hyphe/hyphe_backend/core.tac", line 1793, in index_batch
	    pages, links, autostartpages = yield deferToThread(processor.generate_cache_from_pages_list, page_items, self.corpora[corpus]["options"]["precision_limit"], self.corpora[corpus]['precision_exceptions'], config['DEBUG'] > 0, autostarts=job.get('crawl_arguments', {}).get('start_urls_auto', []))
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 246, in inContext
	    result = inContext.theWork()
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 262, in <lambda>
	    inContext.theWork = lambda: context.call(ctx, func, *args, **kw)
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/context.py", line 118, in callWithContext
	    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	  File "/home/vagrant/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/context.py", line 81, in callWithContext
	    return func(*args,**kw)
	  File "/home/vagrant/hyphe/hyphe_backend/processor.py", line 44, in generate_cache_from_pages_list
	    lrulink = urllru.lru_clean(lrulink)
	  File "/home/vagrant/hyphe/hyphe_backend/lib/urllru.py", line 243, in lru_clean
	    lru = lru_strip_standard_ports(lru)
	  File "/home/vagrant/hyphe/hyphe_backend/lib/urllru.py", line 200, in lru_strip_standard_ports
	    return add_trailing_pipe("|".join([stem for _, _, stem in split_lru_in_stems(lru, False) if not stem in ['t:80', 't:443']]))
	  File "/home/vagrant/hyphe/hyphe_backend/lib/urllru.py", line 52, in split_lru_in_stems
	    elements = lruStems.split(lru.rstrip("|"))
	exceptions.AttributeError: 'list' object has no attribute 'rstrip'

**Comment by boogheta** [comment]
it looks like you're encountering an old bug, did you install from a release zip maybe? unfortunately those are a bit outdated too and we didn't get enough time yet to build the v0.3 release, you should rather install from git sources for now.

**Comment by updiversity** [comment]
no i did it from a git clone of the master branch

**Comment by updiversity** [comment]
I got the problem solved. Basically, my item-pipelines were not properly configured in the settings.

thanks anyway for the feedback

**Comment by boogheta** [comment]
Hi @updiversity, FYI we finally released a new version with new features including a way faster indexing engine and a more generic installation process which should allow you to easily install Hyphe now.
