### ISSUE TITLE
exceptions.ImportError: No module named hyphe_backend

### ISSUE THREAD

**Issue by AsgerGehrt** [medialab/hyphe#205]
I have tried to install the program on several different distros, but I always get stuck when starting hyphe. Current distro: Ubuntu 14.04 Trusty Tahr. Installed by advanced method.

`asger@ubuntu:~/hyphe$ bin/hyphe start
Starting Hyphe's Python core JsonRPC API...
Unhandled Error
Traceback (most recent call last):
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/app.py", line 648, in run
    runApp(config)
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/app.py", line 379, in run
    self.application = self.createOrGetApplication()
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/app.py", line 444, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/app.py", line 455, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "/home/asger/hyphe/hyphe_backend/core.tac", line 24, in <module>
    from hyphe_backend import processor
exceptions.ImportError: No module named hyphe_backend
`

**Comment by boogheta** [comment]
Hi @AsgerGehrt, it seems to me like your installation is somehow incomplete.

Can you do the following and give me the output?
```bash
source $(which virtualenvwrapper.sh)
workon hyphe
lssitepackages
```

It might be fixed only by doing the following (but I doubt it):
```bash
source $(which virtualenvwrapper.sh)
workon hyphe
add2virtualenv ~/hyphe
```

**Comment by AsgerGehrt** [comment]
´´´appdirs-1.4.0.dist-info         pymongo-2.7.dist-info
appdirs.py                      pyOpenSSL-16.2.0.dist-info
appdirs.pyc                     pyparsing-2.1.10.dist-info
attr                            pyparsing.py
attrs-16.3.0.dist-info          pyparsing.pyc
bson                            pystache
cffi                            pystache-0.5.4.dist-info
cffi-1.9.1.dist-info            selenium
_cffi_backend.so                selenium-2.42.1.dist-info
clonevirtualenv.py              service_identity
clonevirtualenv.pyc             service_identity-16.0.0.dist-info
constantly                      setuptools
constantly-15.1.0.dist-info     setuptools-34.1.1.dist-info
cryptography                    simplejson
cryptography-1.7.2.dist-info    simplejson-3.10.0.dist-info
easy_install.py                 six-1.10.0.dist-info
easy_install.pyc                six.py
enum                            six.pyc
enum34-1.1.6.dist-info          stevedore
gridfs                          stevedore-1.20.0.dist-info
idna                            thrift
idna-2.2.dist-info              thrift-0.10.0.dist-info
incremental                     twisted
incremental-16.10.1.dist-info   Twisted-16.6.0.dist-info
ipaddress-1.0.18.dist-info      txjsonrpc
ipaddress.py                    txJSON_RPC-0.5.dist-info
ipaddress.pyc                   txmongo
OpenSSL                         txmongo-0.6.dist-info
packaging                       virtualenv-15.1.0.dist-info
packaging-16.8.dist-info        virtualenv_clone-0.2.6.dist-info
pbr                             _virtualenv_path_extensions.pth
pbr-1.10.0.dist-info            virtualenv.py
pip                             virtualenv.pyc
pip-9.0.1.dist-info             virtualenv_support
pkg_resources                   virtualenvwrapper
pyasn1                          virtualenvwrapper-4.7.2.dist-info
pyasn1-0.1.9.dist-info          virtualenvwrapper-4.7.2-py2.7-nspkg.pth
pyasn1_modules                  wheel
pyasn1_modules-0.0.8.dist-info  wheel-0.29.0.dist-info
pycparser                       zope
pycparser-2.17.dist-info        zope.interface-4.3.3.dist-info
pymongo                         zope.interface-4.3.3-py2.7-nspkg.pth

_virtualenv_path_extensions.pth:
import sys; sys.__plen = len(sys.path)
/home/asger
import sys; new=sys.path[sys.__plen:]; del sys.path[sys.__plen:]; p=getattr(sys,'__egginsert',0); sys.path[p:p]=new; sys.__egginsert = p+len(new)
´´´

**Comment by AsgerGehrt** [comment]
´´´
asger@ubuntu:~/hyphe$ source $(which virtualenvwrapper.sh)
asger@ubuntu:~/hyphe$ workon hyphe
(hyphe) asger@ubuntu:~/hyphe$ add2virtualenv ~/hyphe
´´´

**Comment by AsgerGehrt** [comment]
´´´
Starting Hyphe's Python core JsonRPC API...
Unhandled Error
Traceback (most recent call last):
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/app.py", line 648, in run
    runApp(config)
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
    _SomeApplicationRunner(config).run()
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/app.py", line 379, in run
    self.application = self.createOrGetApplication()
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/app.py", line 444, in createOrGetApplication
    application = getApplication(self.config, passphrase)
--- <exception caught here> ---
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/app.py", line 455, in getApplication
    application = service.loadApplication(filename, style, passphrase)
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/application/service.py", line 411, in loadApplication
    passphrase)
  File "/home/asger/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/persisted/sob.py", line 223, in loadValueFromFile
    eval(codeObj, d, d)
  File "/home/asger/hyphe/hyphe_backend/core.tac", line 27, in <module>
    import processor
exceptions.ImportError: No module named processor


Failed to load application: No module named processor
´´´

**Comment by boogheta** [comment]
This really does not make much sense :/
Are you sure you have all files still unmodified and in the good place?
You should have in hyphe_backend/core.tac a line "from hyphe_backend import processor" which corresponds to the file hyphe_backend/processor.py. Same thing further on for hyphe_backend/lib/config_hci.py

**Comment by AsgerGehrt** [comment]
I am confident that anything else is in good place and unmodified. I agree, it is strange that these simple import from lines are not behaving. :S

**Comment by boogheta** [comment]
Hi, sorry for the long silence, I really have no clue how to better help unfortunately :/

We are in the process of rebuilding a lot of things (cf branch named traph) so we won't be maintaining installation of the actual master branch and will provide an easier install in the coming months, so I'm closing install related issues as of now, but feel free to continue reporting/asking questions in the thread.

**Comment by boogheta** [comment]
Hi @AsgerGehrt, as announced earlier on, we finally released a new version with a more generic installation process which should allow you to easily install Hyphe now.
