### ISSUE TITLE
ERROR: Could not start Hyphe's backend server properly. 

### ISSUE THREAD

**Issue by JMFrancony** [medialab/hyphe#209]
Bonjour,

je suis entrain d'installer hyphe (je n'ai pas touché la configuration de base) et je me heurte à l'erreur suivante :
2017-07-03T15:22:28+0200 [-] Site starting on 6978
2017-07-03T15:22:28+0200 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x7f1cb1d51b90>
2017-07-03T15:22:31+0200 [ERROR - --test-corpus--] Couldn't deploy crawler
2017-07-03T15:22:31+0200 [stderr#error] Exception in thread --test-corpus--:
2017-07-03T15:22:31+0200 [stderr#error] Traceback (most recent call last):
2017-07-03T15:22:31+0200 [stderr#error]   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2017-07-03T15:22:31+0200 [stderr#error]     self.run()
2017-07-03T15:22:31+0200 [stderr#error]   File "/tidebook-storage/hyphe/hyphe_backend/lib/corpus.py", line 158, in run
2017-07-03T15:22:31+0200 [stderr#error]     stderr=subprocess.STDOUT, bufsize=1, universal_newlines=True)
2017-07-03T15:22:31+0200 [stderr#error]   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
2017-07-03T15:22:31+0200 [stderr#error]     errread, errwrite)
2017-07-03T15:22:31+0200 [stderr#error]   File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
2017-07-03T15:22:31+0200 [stderr#error]     raise child_exception
2017-07-03T15:22:31+0200 [stderr#error] OSError: [Errno 2] No such file or directory
2017-07-03T15:22:46+0200 [ERROR - --test-corpus--] Could not start corpus fast enough to create WE creation rule...
2017-07-03T15:22:47+0200 [-] Received SIGTERM, shutting down.
2017-07-03T15:22:47+0200 [-] (TCP Port 6978 Closed)
2017-07-03T15:22:47+0200 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site instance at 0x7f1cb1d51b90>
2017-07-03T15:22:47+0200 [-] Main loop terminated.
2017-07-03T15:22:47+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.

pourriez vous m'indiquer ce qu'il convient de faire ?
cordialement,

**Comment by boogheta** [comment]
Bonjour,

Il semble que plusieurs soucis soient présents, d'une part scrapyd inaccessible et d'autre part la structure mémoire java manquante.

Je peux difficillement vous aider sans plus d'information contextuelle, s'agit-il d'une installation à partir d'une release ou du repo git? Manuelle ou via bin/install.sh ?

**Comment by JMFrancony** [comment]
Bonjour, et merci pour la réponse rapide.
L'installation a été réalisée sur une VM Debian 8.7 livrée "brute". 
j'ai utilisé le bin/install.sh puis, constatant que l'installation était incomplète, je suis revenu sur les étapes de l'installation manuelle à partir du point 2.5) décrit à l'URL : github.com/medialab/hyphe/blob/master/doc/install.md. 

Suite à  vos commentaires, j'ai installé java (1.7.0._131) j'obtiens désormais le message suivant : 
### 
Starting Hyphe's Python core JsonRPC API...
...started...
ERROR: Could not start Hyphe's backend server properly. See log below:

            self._startRunCallbacks(result)
          File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
            self._runCallbacks()
          File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
            current.result = callback(current.result, *args, **kw)
        --- <exception caught here> ---
          File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
            callable(*args, **kwargs)
          File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 278, in stop
            self._team.quit()
          File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 226, in quit
            self._quit.set()
          File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 35, in set
            self.check()
          File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 46, in check
            raise AlreadyQuit()
        twisted._threads._ithreads.AlreadyQuit:

2017-07-04T13:41:30+0200 [-] Main loop terminated.
2017-07-04T13:41:30+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.

Cordialement,

**Comment by boogheta** [comment]
Malheureusement comme indiqué sur la page linkée, nous n'avons encore aucune expérience d'installation réussie sur une debian 8 à ce jour, je ne vous garantis pas le succès.

Pourriez-vous publier un log plus complet que les dernières lignes? (log/hyphe-core.log)

**Comment by JMFrancony** [comment]
Voilà, ce que cela donne : 

2017-07-03T15:22:28+0200 [-] Loading /tidebook-storage/hyphe/hyphe_backend/core.tac...
2017-07-03T15:22:28+0200 [-] Loaded.
2017-07-03T15:22:28+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.5.0 (/home/jfrancon/.virtualenvs/hyphe/bin/python 2.7.9) starting up.
2017-07-03T15:22:28+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2017-07-03T15:22:28+0200 [-] Site starting on 6978
2017-07-03T15:22:28+0200 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x7f1cb1d51b90>
2017-07-03T15:22:31+0200 [ERROR - --test-corpus--] Couldn't deploy crawler
2017-07-03T15:22:31+0200 [stderr#error] Exception in thread --test-corpus--:
2017-07-03T15:22:31+0200 [stderr#error] Traceback (most recent call last):
2017-07-03T15:22:31+0200 [stderr#error]   File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
2017-07-03T15:22:31+0200 [stderr#error]     self.run()
2017-07-03T15:22:31+0200 [stderr#error]   File "/tidebook-storage/hyphe/hyphe_backend/lib/corpus.py", line 158, in run
2017-07-03T15:22:31+0200 [stderr#error]     stderr=subprocess.STDOUT, bufsize=1, universal_newlines=True)
2017-07-03T15:22:31+0200 [stderr#error]   File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
2017-07-03T15:22:31+0200 [stderr#error]     errread, errwrite)
2017-07-03T15:22:31+0200 [stderr#error]   File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
2017-07-03T15:22:31+0200 [stderr#error]     raise child_exception
2017-07-03T15:22:31+0200 [stderr#error] OSError: [Errno 2] No such file or directory
2017-07-03T15:22:46+0200 [ERROR - --test-corpus--] Could not start corpus fast enough to create WE creation rule...
2017-07-03T15:22:47+0200 [-] Received SIGTERM, shutting down.
2017-07-03T15:22:47+0200 [-] (TCP Port 6978 Closed)
2017-07-03T15:22:47+0200 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site instance at 0x7f1cb1d51b90>
2017-07-03T15:22:47+0200 [-] Main loop terminated.
2017-07-03T15:22:47+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.
2017-07-04T13:40:59+0200 [-] Loading /tidebook-storage/hyphe/hyphe_backend/core.tac...
2017-07-04T13:40:59+0200 [-] Loaded.
2017-07-04T13:40:59+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] twistd 17.5.0 (/home/jfrancon/.virtualenvs/hyphe/bin/python 2.7.9) starting up.
2017-07-04T13:40:59+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] reactor class: twisted.internet.epollreactor.EPollReactor.
2017-07-04T13:40:59+0200 [-] Site starting on 6978
2017-07-04T13:40:59+0200 [twisted.web.server.Site#info] Starting factory <twisted.web.server.Site instance at 0x7f045eb60710>
2017-07-04T13:41:30+0200 [-] Received SIGTERM, shutting down.
2017-07-04T13:41:30+0200 [ERROR - --test-corpus--] Could not start corpus fast enough to create WE creation rule...
2017-07-04T13:41:30+0200 [-] (TCP Port 6978 Closed)
2017-07-04T13:41:30+0200 [twisted.web.server.Site#info] Stopping factory <twisted.web.server.Site instance at 0x7f045eb60710>
2017-07-04T13:41:30+0200 [stdout#info] ERROR --test-corpus--: Could not start corpus
2017-07-04T13:41:30+0200 [stdout#info] {'ready': False, 'status': 'stopped', 'message': 'Corpus is not started', 'corpus_id': '--test-corpus--'}
2017-07-04T13:41:30+0200 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1117, in _cbDeferred
	    self.callback(self.resultList)
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
	    self._startRunCallbacks(result)
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 278, in stop
	    self._team.quit()
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 226, in quit
	    self._quit.set()
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 35, in set
	    self.check()
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 46, in check
	    raise AlreadyQuit()
	twisted._threads._ithreads.AlreadyQuit: 
	
2017-07-04T13:41:30+0200 [-] Unhandled Error
	Traceback (most recent call last):
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 1117, in _cbDeferred
	    self.callback(self.resultList)
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 459, in callback
	    self._startRunCallbacks(result)
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 567, in _startRunCallbacks
	    self._runCallbacks()
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/defer.py", line 653, in _runCallbacks
	    current.result = callback(current.result, *args, **kw)
	--- <exception caught here> ---
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/internet/base.py", line 441, in _continueFiring
	    callable(*args, **kwargs)
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/python/threadpool.py", line 278, in stop
	    self._team.quit()
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/_threads/_team.py", line 226, in quit
	    self._quit.set()
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 35, in set
	    self.check()
	  File "/home/jfrancon/.virtualenvs/hyphe/local/lib/python2.7/site-packages/twisted/_threads/_convenience.py", line 46, in check
	    raise AlreadyQuit()
	twisted._threads._ithreads.AlreadyQuit: 
	
2017-07-04T13:41:30+0200 [-] Main loop terminated.
2017-07-04T13:41:30+0200 [twisted.scripts._twistd_unix.UnixAppLogger#info] Server Shut Down.

**Comment by boogheta** [comment]
Désolé pour le long silence, je dois avouer sécher en l'état.
Comme indiqué par ailleurs, nous sommes en cours d'une refonte assez profonde et n'allons donc plus prendre le temps de maintenir la version passée et devrions avoir une future version plus simple à installer dans les prochains mois. Du coup je ferme les issues relatives à l'install pour le moment, mais n'hésitez pas à réalimenter ce thread si vous avez du nouveau.

**Comment by boogheta** [comment]
Bonjour @JMFrancony, comme annoncé plus tôt, nous avons finalement publié une nouvelle version avec une méthode d'installation plus générique qui devrait désormais vous permettre d'installer Hyphe beaucoup plus simplement.
