### ISSUE TITLE
Bug in explore Webentity URL front app

### ISSUE THREAD

**Issue by paulgirard** [medialab/hyphe#216]
Unable to push branch in explorer tree lru: s:http|h:net|h:online|h:www| TypeError: Cannot read property 'children' of undefined
    at pushBranch (http://localhost:8000/views/webentity.js:993:24)
    at http://localhost:8000/views/webentity.js:1020:11
    at Array.forEach (native)
    at http://localhost:8000/views/webentity.js:1019:21
    at Array.forEach (native)
    at buildExplorerTree (http://localhost:8000/views/webentity.js:1018:29)
    at checkTripleLoading (http://localhost:8000/views/webentity.js:762:9)
    at api.getParentWebentities.$scope.status.message (http://localhost:8000/views/webentity.js:736:11)
    at http://localhost:8000/js/service_hyphe_api.js:651:13
    at http://localhost:8000/bower_assets/angular/angular.min.js:80:396

**Comment by paulgirard** [comment]
That was due to the method get_webEntity_parentwebentities returning all WEs !
