### ISSUE TITLE
Occasionnal stack on open/create traph socket

### ISSUE THREAD

**Issue by boogheta** [medialab/hyphe#221]
```
2017-09-04 15:09:34 [-] Unhandled error in Deferred:
2017-09-04 15:09:34 [-] (debug:  C: Deferred was created:
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/bin/twistd", line 9, in <module>
	 C:    load_entry_point('Twisted==17.5.0', 'console_scripts', 'twistd')()
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
	 C:    app.run(runApp, ServerOptions)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
	 C:    runApp(config)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
	 C:    _SomeApplicationRunner(config).run()
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/application/app.py", line 384, in run
	 C:    self.postApplication()
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 262, in postApplication
	 C:    self.startReactor(None, self.oldstdout, self.oldstderr)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/application/app.py", line 396, in startReactor
	 C:    self.config, oldstdout, oldstderr, self.profiler, reactor)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/application/app.py", line 311, in runReactorWithLogging
	 C:    reactor.run()
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
	 C:    self.mainLoop()
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/base.py", line 1255, in mainLoop
	 C:    self.doIteration(t)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/epollreactor.py", line 235, in doPoll
	 C:    log.callWithLogger(selectable, _drdw, selectable, fd, event)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/python/log.py", line 103, in callWithLogger
	 C:    return callWithContext({"system": lp}, func, *args, **kw)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/python/log.py", line 86, in callWithContext
	 C:    return context.call({ILogContext: newCtx}, func, *args, **kw)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/python/context.py", line 122, in callWithContext
	 C:    return self.currentContext().callWithContext(ctx, func, *args, **kw)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/python/context.py", line 85, in callWithContext
	 C:    return func(*args,**kw)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/posixbase.py", line 597, in _doReadOrWrite
	 C:    why = selectable.doRead()
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/process.py", line 291, in doRead
	 C:    return fdesc.readFromFD(self.fd, self.dataReceived)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/fdesc.py", line 94, in readFromFD
	 C:    callback(output)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/process.py", line 295, in dataReceived
	 C:    self.proc.childDataReceived(self.name, data)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/process.py", line 961, in childDataReceived
	 C:    self.proto.childDataReceived(name, data)
	 C:  File "/store/hyphe-home/dev-mathieu/hyphe_backend/traph/client.py", line 247, in childDataReceived
	 C:    self.connectClient()
	 C:  File "/store/hyphe-home/dev-mathieu/hyphe_backend/traph/client.py", line 241, in connectClient
	 C:    UNIXClientEndpoint(reactor, self.socket).connect(t)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 1186, in connect
	 C:    wf = _WrappingFactory(protocolFactory)
	 C:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 189, in __init__
	 C:    self._onConnection = defer.Deferred(canceller=self._canceller)
	 I: First Invoker was:
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/bin/twistd", line 9, in <module>
	 I:    load_entry_point('Twisted==17.5.0', 'console_scripts', 'twistd')()
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 29, in run
	 I:    app.run(runApp, ServerOptions)
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/application/app.py", line 662, in run
	 I:    runApp(config)
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/scripts/twistd.py", line 25, in runApp
	 I:    _SomeApplicationRunner(config).run()
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/application/app.py", line 384, in run
	 I:    self.postApplication()
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/scripts/_twistd_unix.py", line 262, in postApplication
	 I:    self.startReactor(None, self.oldstdout, self.oldstderr)
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/application/app.py", line 396, in startReactor
	 I:    self.config, oldstdout, oldstderr, self.profiler, reactor)
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/application/app.py", line 311, in runReactorWithLogging
	 I:    reactor.run()
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/base.py", line 1243, in run
	 I:    self.mainLoop()
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/base.py", line 1252, in mainLoop
	 I:    self.runUntilCurrent()
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/base.py", line 878, in runUntilCurrent
	 I:    call.func(*call.args, **call.kw)
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/tcp.py", line 576, in doConnect
	 I:    self.failIfNotConnected(error.getConnectError((connectResult, strerror(connectResult))))
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/tcp.py", line 453, in failIfNotConnected
	 I:    self.connector.connectionFailed(failure.Failure(err))
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/base.py", line 1128, in connectionFailed
	 I:    self.factory.clientConnectionFailed(self, reason)
	 I:  File "/store/hyphe-home/.virtualenvs/hyphe-traph/lib/python2.7/site-packages/twisted/internet/endpoints.py", line 263, in clientConnectionFailed
	 I:    self._onConnection.errback(reason)
	)
	Traceback (most recent call last):
	Failure: twisted.internet.error.ConnectError: An error occurred while connecting: 2: No such file or directory.
```

**Comment by boogheta** [comment]
Looks like the fix wasn't sufficient :/
